#!/bin/bash
# threat-model-generator.sh — Auto-generate or enrich a threat model from project context
#
# Reads project documentation, data models, configs, and code patterns to
# produce a comprehensive threat-model.json without requiring manual interviews.
#
# Context sources (in priority order):
#   1. CLAUDE.md / SESSION-CONTEXT.md — product rules, decisions, user types
#   2. README.md — product description, target audience, purpose
#   3. Data models — PII fields, relationships, sensitive data
#   4. Route/router analysis — auth patterns, file uploads, external calls
#   5. Privacy policy / terms — legal obligations
#   6. Package.json / requirements.txt — external service integrations
#   7. .env.example — API keys and services used
#   8. App store metadata — age ratings, content categories
#
# Output: A context-report.md file that Claude reads to generate/update threat-model.json
#
# Usage:
#   threat-model-generator.sh [project-dir]
#   Then: claude 'read context-report.md and generate/update threat-model.json'

set -euo pipefail

PROJECT_DIR="${1:-$(pwd)}"
REPORT="$PROJECT_DIR/context-report.md"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    head -18 "$0" | grep '^#' | sed 's/^# \?//'
    exit 0
fi

echo "🔍 Gathering business context from: $(basename "$PROJECT_DIR")"
echo "================================================"
echo ""

# Initialize report
cat > "$REPORT" <<'HEADER'
# Project Context Report — Auto-Generated for Threat Model

This report was generated by `threat-model-generator.sh` by scanning
project documentation, code, and configuration. Feed this to Claude
to generate or update `threat-model.json`.

---

HEADER

# =========================================================================
# 1. Product documentation
# =========================================================================

echo "📄 Scanning documentation..."

for doc in CLAUDE.md SESSION-CONTEXT.md README.md; do
    if [ -f "$PROJECT_DIR/$doc" ]; then
        echo "  + $doc"
        echo "## From $doc" >> "$REPORT"
        echo "" >> "$REPORT"
        echo '```' >> "$REPORT"
        head -100 "$PROJECT_DIR/$doc" >> "$REPORT"
        echo '```' >> "$REPORT"
        echo "" >> "$REPORT"
    fi
done

# App store / marketing docs
for doc in app-store-assets.md app_flow_document.md project_requirements_document.md security_guideline_document.md; do
    if [ -f "$PROJECT_DIR/$doc" ]; then
        echo "  + $doc"
        echo "## From $doc" >> "$REPORT"
        echo "" >> "$REPORT"
        echo '```' >> "$REPORT"
        head -80 "$PROJECT_DIR/$doc" >> "$REPORT"
        echo '```' >> "$REPORT"
        echo "" >> "$REPORT"
    fi
done

# Legal docs
for doc in legal/privacy.html legal/terms.html privacy-policy.md terms.md; do
    if [ -f "$PROJECT_DIR/$doc" ]; then
        echo "  + $doc (legal)"
        echo "## Legal: $doc" >> "$REPORT"
        echo "" >> "$REPORT"
        echo '```' >> "$REPORT"
        head -60 "$PROJECT_DIR/$doc" >> "$REPORT"
        echo '```' >> "$REPORT"
        echo "" >> "$REPORT"
    fi
done

# =========================================================================
# 2. Data models — identify PII and sensitive fields
# =========================================================================

echo "📊 Scanning data models..."

echo "## Data Models and Sensitive Fields" >> "$REPORT"
echo "" >> "$REPORT"

# Python models (Beanie/Pydantic)
MODEL_FILES=""
for dir in core/models core/schemas app/models app/schemas; do
    if [ -d "$PROJECT_DIR/$dir" ]; then
        for f in "$PROJECT_DIR/$dir"/*.py; do
            [ -f "$f" ] || continue
            MODEL_FILES="$MODEL_FILES $f"
        done
    fi
done

# TypeScript types/models
for dir in src/types src/models src/schemas; do
    if [ -d "$PROJECT_DIR/$dir" ]; then
        for f in "$PROJECT_DIR/$dir"/*.ts; do
            [ -f "$f" ] || continue
            MODEL_FILES="$MODEL_FILES $f"
        done
    fi
done

PII_PATTERNS="email|password|phone|address|ssn|social_security|birth|age|name|first_name|last_name|location|ip_address|credit_card|token|secret|voice|audio|recording|biometric|child|minor|dob|date_of_birth|legal|criminal|sentence|conviction|parole"

if [ -n "$MODEL_FILES" ]; then
    echo "### PII and Sensitive Fields Found" >> "$REPORT"
    echo "" >> "$REPORT"
    echo '```' >> "$REPORT"
    for f in $MODEL_FILES; do
        matches=$(grep -inE "$PII_PATTERNS" "$f" 2>/dev/null | head -20)
        if [ -n "$matches" ]; then
            echo "--- $(basename "$f") ---" >> "$REPORT"
            echo "$matches" >> "$REPORT"
            echo "" >> "$REPORT"
            echo "  + $(basename "$f") — found PII fields"
        fi
    done
    echo '```' >> "$REPORT"
    echo "" >> "$REPORT"
fi

# =========================================================================
# 3. User types and auth patterns
# =========================================================================

echo "🔐 Scanning auth patterns..."

echo "## User Types and Auth Patterns" >> "$REPORT"
echo "" >> "$REPORT"
echo '```' >> "$REPORT"

# Find role definitions
ROLE_DEFS=$(grep -rnE "class.*Role|UserRole|role.*=.*['\"]|enum.*Role|type.*Role" \
    "$PROJECT_DIR/core" "$PROJECT_DIR/src" "$PROJECT_DIR/app" 2>/dev/null | \
    grep -v node_modules | grep -v __pycache__ | head -20)

if [ -n "$ROLE_DEFS" ]; then
    echo "Role definitions:" >> "$REPORT"
    echo "$ROLE_DEFS" >> "$REPORT"
    echo "" >> "$REPORT"
    echo "  + Found role definitions"
fi

# Find auth middleware/dependencies
AUTH_PATTERNS=$(grep -rnE "get_current_user|get_current_admin|get_current_moderator|requireAuth|isAdmin|authenticate|verify_token|jwt\.verify" \
    "$PROJECT_DIR/core" "$PROJECT_DIR/src" "$PROJECT_DIR/app" 2>/dev/null | \
    grep -v node_modules | grep -v __pycache__ | head -20)

if [ -n "$AUTH_PATTERNS" ]; then
    echo "Auth patterns:" >> "$REPORT"
    echo "$AUTH_PATTERNS" >> "$REPORT"
    echo "" >> "$REPORT"
    echo "  + Found auth patterns"
fi

echo '```' >> "$REPORT"
echo "" >> "$REPORT"

# =========================================================================
# 4. External integrations
# =========================================================================

echo "🔌 Scanning integrations..."

echo "## External Integrations" >> "$REPORT"
echo "" >> "$REPORT"

# Check package.json / requirements.txt
for pkg_file in package.json requirements.txt pyproject.toml; do
    if [ -f "$PROJECT_DIR/$pkg_file" ]; then
        echo "### From $pkg_file" >> "$REPORT"
        echo '```' >> "$REPORT"
        grep -iE "stripe|sendgrid|twilio|aws|firebase|openai|anthropic|supabase|redis|mongo|postgres|pillow|celery|rabbitmq" \
            "$PROJECT_DIR/$pkg_file" 2>/dev/null | head -15 >> "$REPORT" || true
        echo '```' >> "$REPORT"
        echo "" >> "$REPORT"
    fi
done

# Check .env.example for service keys
for env_file in .env.example .env.sample; do
    if [ -f "$PROJECT_DIR/$env_file" ]; then
        echo "### From $env_file (services detected)" >> "$REPORT"
        echo '```' >> "$REPORT"
        grep -iE "KEY|SECRET|TOKEN|URL|DSN|URI" "$PROJECT_DIR/$env_file" 2>/dev/null | \
            sed 's/=.*/=<redacted>/' | head -20 >> "$REPORT" || true
        echo '```' >> "$REPORT"
        echo "" >> "$REPORT"
        echo "  + $env_file — found service configs"
    fi
done

# =========================================================================
# 5. File upload endpoints
# =========================================================================

echo "📎 Scanning file upload patterns..."

echo "## File Upload Endpoints" >> "$REPORT"
echo "" >> "$REPORT"
echo '```' >> "$REPORT"

UPLOAD_MATCHES=$(grep -rnE "UploadFile|multer|File\(\.\.\.\)|multipart|upload|@file" \
    "$PROJECT_DIR/src" "$PROJECT_DIR/app" 2>/dev/null | \
    grep -v node_modules | grep -v __pycache__ | head -20)

if [ -n "$UPLOAD_MATCHES" ]; then
    echo "$UPLOAD_MATCHES" >> "$REPORT"
    echo "  + Found file upload endpoints"
else
    echo "No file upload endpoints detected" >> "$REPORT"
fi

echo '```' >> "$REPORT"
echo "" >> "$REPORT"

# =========================================================================
# 6. Route summary
# =========================================================================

echo "📡 Scanning routes..."

echo "## API Routes" >> "$REPORT"
echo "" >> "$REPORT"

# Express
if [ -d "$PROJECT_DIR/src/routes" ]; then
    echo "### Express Routes" >> "$REPORT"
    echo '```' >> "$REPORT"
    for f in "$PROJECT_DIR/src/routes"/*.ts "$PROJECT_DIR/src/routes"/*.js; do
        [ -f "$f" ] || continue
        echo "$(basename "$f"):" >> "$REPORT"
        grep -E "router\.(get|post|put|delete|patch)" "$f" 2>/dev/null | head -10 >> "$REPORT"
        echo "" >> "$REPORT"
    done
    echo '```' >> "$REPORT"
fi

# FastAPI
if [ -d "$PROJECT_DIR/app/routers" ]; then
    echo "### FastAPI Routers" >> "$REPORT"
    echo '```' >> "$REPORT"
    for f in "$PROJECT_DIR/app/routers"/*.py; do
        [ -f "$f" ] || continue
        basename_f=$(basename "$f" .py)
        [ "$basename_f" = "__init__" ] && continue
        echo "$(basename "$f"):" >> "$REPORT"
        grep -E "@router\.(get|post|put|delete|patch)" "$f" 2>/dev/null | head -10 >> "$REPORT"
        echo "" >> "$REPORT"
    done
    echo '```' >> "$REPORT"
fi

echo "" >> "$REPORT"

# =========================================================================
# 7. Existing threat model (for enrichment)
# =========================================================================

if [ -f "$PROJECT_DIR/threat-model.json" ]; then
    echo "## Existing Threat Model" >> "$REPORT"
    echo "" >> "$REPORT"
    echo '```json' >> "$REPORT"
    cat "$PROJECT_DIR/threat-model.json" >> "$REPORT"
    echo '```' >> "$REPORT"
    echo "" >> "$REPORT"
fi

# =========================================================================
# Instructions for Claude
# =========================================================================

cat >> "$REPORT" <<'INSTRUCTIONS'

---

## Instructions for Claude

Based on the context above, generate or update `threat-model.json` with:

1. **Project description** — what the product does, who uses it
2. **Architecture** — frameworks, databases, external services
3. **Data sensitivity** — what PII exists, regulatory requirements
4. **User types** — all roles found in auth patterns
5. **Risk profile** — categorized risk levels for each concern area
6. **Risks array** — one entry per specific risk, with:
   - `id`: Project-prefix + number (e.g., CLEM-001, RB-001)
   - `name`: Short descriptive name
   - `severity`: critical / high / medium / low
   - `description`: What could go wrong and why it matters
   - `test_pattern`: Regex pattern for security-test-audit.sh to verify coverage
   - `endpoints`: Which API endpoints are affected

**Severity guidelines:**
- **critical**: Children's data, biometric data, payment fraud, COPPA/GDPR violations
- **high**: PII exposure, privilege escalation, file upload abuse, auth bypass
- **medium**: Content injection (XSS), email abuse, enumeration
- **low**: Information disclosure in error messages, missing rate limits on non-sensitive endpoints

**Include project-specific risks** that generic security tests wouldn't catch.
For example:
- If the product serves children → COPPA compliance risks
- If it handles legal proceedings → data integrity and tampering risks
- If it uses AI generation → prompt injection risks
- If it handles voice/audio → biometric data risks
- If it has a role system → privilege escalation risks

INSTRUCTIONS

echo ""
echo "================================================"
echo "✅ Context report written to: $REPORT"
echo ""
echo "Next step — run Claude to generate/update the threat model:"
echo "  cd $PROJECT_DIR"
echo "  claude 'read context-report.md and update threat-model.json'"
echo ""
echo "The report contains $(wc -l < "$REPORT" | tr -d ' ') lines of business context."
