#!/bin/bash
# weekly-coverage-audit.sh — Run E2E coverage audit across projects and report results
#
# Designed to run on a weekly cron (e.g., Monday 8am) or on demand.
# Scans configured project directories, runs audit-e2e-coverage.sh on each,
# and posts a summary to GitHub Discussions, a file, or stdout.
#
# Usage:
#   weekly-coverage-audit.sh [options]
#
# Options:
#   --projects DIR1,DIR2,...   Comma-separated project directories to audit
#   --output github            Post to GitHub Discussion (requires gh CLI)
#   --output file              Write to ~/.claude/coverage-report.md
#   --output stdout            Print to stdout (default)
#   --repo OWNER/REPO          GitHub repo for discussion posts
#   --category CATEGORY        Discussion category (default: "QA Reports")
#
# Environment:
#   CLAUDE_QA_PROJECTS   Comma-separated project directories (alternative to --projects)
#
# Cron example (Monday 8am):
#   0 8 * * 1 ~/.claude/scripts/weekly-coverage-audit.sh --projects /path/to/proj1,/path/to/proj2 --output file

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECTS="${CLAUDE_QA_PROJECTS:-}"
OUTPUT_MODE="stdout"
REPO=""
CATEGORY="QA Reports"
REPORT_FILE="$HOME/.claude/coverage-report.md"

while [ $# -gt 0 ]; do
    case "$1" in
        --projects)  PROJECTS="$2"; shift 2 ;;
        --output)    OUTPUT_MODE="$2"; shift 2 ;;
        --repo)      REPO="$2"; shift 2 ;;
        --category)  CATEGORY="$2"; shift 2 ;;
        --help|-h)
            head -20 "$0" | grep '^#' | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

if [ -z "$PROJECTS" ]; then
    echo "Error: No projects specified."
    echo "Use --projects dir1,dir2 or set CLAUDE_QA_PROJECTS env var."
    echo "Run with --help for usage."
    exit 2
fi

DATE=$(date +"%Y-%m-%d")
REPORT="# Weekly E2E Coverage Report — $DATE\n\n"
TOTAL_GAPS=0

IFS=',' read -ra PROJECT_LIST <<< "$PROJECTS"

for project_dir in "${PROJECT_LIST[@]}"; do
    project_dir=$(echo "$project_dir" | xargs)  # trim whitespace

    if [ ! -d "$project_dir" ]; then
        REPORT+="## $(basename "$project_dir")\n\n"
        REPORT+="> **Skipped** — directory not found: \`$project_dir\`\n\n"
        continue
    fi

    PROJECT_NAME=$(basename "$project_dir")
    REPORT+="## $PROJECT_NAME\n\n"

    # Run audit in JSON mode
    AUDIT_JSON=$("$SCRIPTS_DIR/audit-e2e-coverage.sh" --json "$project_dir" 2>/dev/null) || true
    GAPS=$(echo "$AUDIT_JSON" | jq -r '.gaps // 0' 2>/dev/null || echo "?")
    STATUS=$(echo "$AUDIT_JSON" | jq -r '.status // "unknown"' 2>/dev/null || echo "unknown")

    if [ "$STATUS" = "all_covered" ]; then
        REPORT+="  All routes have E2E specs\n\n"
    elif [ "$GAPS" != "0" ] && [ "$GAPS" != "?" ]; then
        REPORT+="  **$GAPS route(s) missing E2E coverage**\n\n"
        TOTAL_GAPS=$((TOTAL_GAPS + GAPS))
    else
        REPORT+="  Could not determine coverage (no routes detected or audit failed)\n\n"
    fi

    # Also run detailed (human-readable) audit and capture it
    DETAIL=$("$SCRIPTS_DIR/audit-e2e-coverage.sh" "$project_dir" 2>/dev/null) || true
    if [ -n "$DETAIL" ]; then
        REPORT+="\`\`\`\n$DETAIL\n\`\`\`\n\n"
    fi
done

# --- Flaky test summary ---
if [ -x "$SCRIPTS_DIR/flaky-test-detector.sh" ]; then
    FLAKY_JSON=$("$SCRIPTS_DIR/flaky-test-detector.sh" --json 2>/dev/null) || true
    if [ -n "$FLAKY_JSON" ]; then
        FLAKY_COUNT=$(echo "$FLAKY_JSON" | jq '.flaky_files | length' 2>/dev/null || echo "0")
        CHRONIC_COUNT=$(echo "$FLAKY_JSON" | jq '.chronic_failures | length' 2>/dev/null || echo "0")
        TOTAL_RUNS=$(echo "$FLAKY_JSON" | jq '.summary.total_runs' 2>/dev/null || echo "0")
        PASS_RATE=$(echo "$FLAKY_JSON" | jq '.summary | (if .total_runs > 0 then (.passed / .total_runs * 100 | floor) else 0 end)' 2>/dev/null || echo "?")

        REPORT+="## QA Hook Health\n\n"
        REPORT+="| Metric | Value |\n|--------|-------|\n"
        REPORT+="| Total hook runs (7d) | $TOTAL_RUNS |\n"
        REPORT+="| Pass rate | ${PASS_RATE}% |\n"
        REPORT+="| Flaky files | $FLAKY_COUNT |\n"
        REPORT+="| Chronic failures | $CHRONIC_COUNT |\n\n"
    fi
fi

REPORT+="---\n\n"
REPORT+="**Total gaps across all projects: $TOTAL_GAPS**\n\n"
REPORT+="_Generated by [claude-qa-hooks](https://github.com/litsonco/claude-qa-hooks) weekly audit_\n"

# --- Output ---
case "$OUTPUT_MODE" in
    stdout)
        echo -e "$REPORT"
        ;;
    file)
        echo -e "$REPORT" > "$REPORT_FILE"
        echo "Report written to $REPORT_FILE"
        ;;
    github)
        if [ -z "$REPO" ]; then
            echo "Error: --repo is required for GitHub output"
            exit 2
        fi
        echo -e "$REPORT" | gh api "repos/$REPO/discussions" \
            -f title="Weekly E2E Coverage Report — $DATE" \
            -f body="$(echo -e "$REPORT")" \
            -f category_name="$CATEGORY" \
            2>/dev/null && echo "Posted to GitHub Discussions" || \
            echo "Failed to post. Falling back to stdout:" && echo -e "$REPORT"
        ;;
    *)
        echo "Unknown output mode: $OUTPUT_MODE"
        exit 2
        ;;
esac

exit $TOTAL_GAPS
